### ISSUE TITLE
Change the way intents of a transcript are stored.

### ISSUE THREAD

**Issue by chenikabukes** [Dhairya-Khara/TLI-Voiceflow-Project#22]

**Comment by aidanmrli** [comment]
Done as intended for one user. Consider changing this to a hashmap later on.

intents is Array, each array location stores one dictionary. dictionary keys are the intent strings in a transcript(s), value is a list of length 2: list[0] is the number of times intent appears in transcript, list[1] is another dictionary containing related intents as keys and number of appearances as the values

the intents Array has the aggregate of all transcripts in location 0, and each other location is an individual transcript
