### ISSUE TITLE
Finalize general UI layout

### ISSUE THREAD

**Issue by chenikabukes** [Dhairya-Khara/TLI-Voiceflow-Project#60]

**Comment by aidanmrli** [comment]
Experimenting with Figma for major UI changes including colour scheme, layout of components in the view

**Comment by krishnacheemalapati** [comment]
Work on implementing the pages and components depicted on the Figma [here](https://www.figma.com/file/kGX2QtXMlOhjTcgt2icNgt/TLI-Voiceflow-Project-Outline?t=gWfIKrv00i8eAsDD-1)
and making all of the features depicted on the Figma are functional (i.e. buttons, login, transcript upload, and more).

**Comment by aidanmrli** [comment]
Done as of Thursday 1 December 2022. In the future (if we worked on this full-time), think about accessibility of the website and how it can be designed to be accessible by more people with various disabilities (colour-blind, slow internet, poor technological skills, browser issues, etc)
