### ISSUE TITLE
Intent names and frequency on hover

### ISSUE THREAD

**Issue by chenikabukes** [Dhairya-Khara/TLI-Voiceflow-Project#61]

**Comment by BerkeAltiparmak** [comment]
Decided to present these on Model as well upon clicking a bubble. 
The logic:
The user clicks a bubble.
The intent that is on that bubble is identified.
The intent's name, frequency, and associated are retrieved from the id of the bubble (the bubble's id stores all these info in a string).
Presenting these pieces of information on a React Modal.

**Comment by aidanmrli** [comment]
As of 18 days prior to 5 December 2022, this is shown in a separate section (React Modal) of the User Interface in a box when the user clicks on this.
