### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by chenikabukes** [Dhairya-Khara/TLI-Voiceflow-Project#63]

**Comment by BerkeAltiparmak** [comment]
Deployment to AWS. Can use the resources provided by the TAs to get an inspiration, but need to find more resources online because we are suing JavaScript. Need to discuss if we want Docker in our project.

**Comment by BerkeAltiparmak** [comment]
We can deploy through the trick Dhairya was talking about

**Comment by aidanmrli** [comment]
For the benefit of everyone who missed the discussion (including Paul, Affan, Ekagra if you are looking into our issues), we are going to use Heroku to deploy with the GitHub Student Pack benefits.

**Comment by aidanmrli** [comment]
Closed: Deployed on Heroku as of Nov 29, 2022. Please ask the TAs when we need to host it until - we do not have unlimited credits.
