### ISSUE TITLE
Plan out the 'TOOL'

### ISSUE THREAD

**Issue by chenikabukes** [Dhairya-Khara/TLI-Voiceflow-Project#64]

**Comment by aidanmrli** [comment]
The tool is for manually labelling transcripts that do not already have intents for messages with intents.

**Comment by aidanmrli** [comment]
After having done some research, this is something ambitious that we do not have the time to do for a variety of transcripts. The real utility of this feature would be mainly when the corpus of labeled data would be sufficiently large to carry out supervised machine learning to predict labels for future messages/utterances, which is arguably beyond the reasonable scope of the project.
