### ISSUE TITLE
Make a Test Suite using Jest

### ISSUE THREAD

**Issue by chenikabukes** [Dhairya-Khara/TLI-Voiceflow-Project#73]
Aidan 16 Nov: will start on the back-end, pay back the debt by the end of the week before Milestone 4 submission

**Comment by aidanmrli** [comment]
Aidan 22 Nov: test suite including unit tests for all Use Cases has been made. see PR #76 . Currently using MongoDB memory model for the user schema to save in certain test cases. In the future, we could figure out how to make use of Jest Mock functions better to mimic things like the jsonwebtoken issued, or adding names to transcript objects.
