### ISSUE TITLE
A way to get voiceflow email, password and diagram id.

### ISSUE THREAD

**Issue by Dhairya-Khara** [Dhairya-Khara/TLI-Voiceflow-Project#74]
So far the email and password is hard coded. Obviously, we cannot have that in the final project. The two things we could do is:

- Ask the user to log in with their voiceflow account and use that information to make blocks
- Ask the user to enter their email and password everytime they want to create a intent block.

**Comment by aidanmrli** [comment]
Done: the user logs in with their Voiceflow account to create blocks.
