### ISSUE TITLE
Fixing "same name file" issue

### ISSUE THREAD

**Issue by BerkeAltiparmak** [Dhairya-Khara/TLI-Voiceflow-Project#77]
Problem:
When you try to upload two transcripts of the same name, the program crashes.

Solution:
When a program receives a transcript, it does these things:

frontend sends data to backend
frontend waits to hear back from backend before doing anything (frontend doesn't add a button)
backend checks if transcript of the same name exists
if yes, backend throws an error, and doesn't identify the intents in the transcript
if frontend receives an error message, frontend doesn't add a button for the new transcript.

**Comment by BerkeAltiparmak** [comment]
Problem:
When you try to upload two transcripts of the same name, the program crashes.

Solution:
When a program receives a transcript, it does these things:

- frontend sends data to backend
- frontend waits to hear back from backend before doing anything (frontend doesn't add a button)
- backend checks if transcript of the same name exists
- if yes, backend throws an error, and doesn't identify the intents in the transcript
- if frontend receives an error message, frontend doesn't add a button for the new transcript.

**Comment by aidanmrli** [comment]
Closed on Mon 5 Dec. Program does not crash when uploading files with the same name.
