### ISSUE TITLE
Update Documentation for transcriptUploadInteractor (support MultiWOZ update)

### ISSUE THREAD

**Issue by aidanmrli** [Dhairya-Khara/TLI-Voiceflow-Project#96]
See #83 : updated transcriptUploadInteractor, extending it to support not only single transcripts but multiple MultiWOZ transcripts in one file.

Aidan Thurs 1 Dec: Managed to enable proper updating of user's intents such that we can upload one dialogue with multiple transcripts in one go, and see the aggregate visualization of all the transcripts with the Visualize All function. Ensured this adheres to the Open-Closed Principle because we still support single transcripts like we did previously, but we also have the ability to upload multiple transcripts in one file. This also agrees with the Liskov Substitution principle because we can substitute a single transcript into a multiple transcript format.

**Comment by aidanmrli** [comment]
Aidan 5 Dec: Have updated the headers of all the Use Case files with new features, and fixed some erroneous documentation in Get Use Case files. Need to check that these changes have been deployed to JSDoc with @BerkeAltiparmak .

Should think about updating the main README if necessary.

**Comment by BerkeAltiparmak** [comment]
The changes on the structure of the code (MultiWOZ update + having Transcript as an entity) has been reflected on the documentation page using JSDoc. Next is to deploy it again on the documentation website.
